services:
  postgres:
    container_name: ${APP_NAME}-postgres
    build:
      context: .
      dockerfile: ../../docker/${APP_NAME}/postgres/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_HOST: '${DB_HOST}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ../../db/${APP_NAME}/data/:/var/lib/postgresql/data
  php-fpm:
    container_name: ${APP_NAME}-php-fpm
    build:
      context: .
      dockerfile: ../../docker/${APP_NAME}/php-fpm/Dockerfile
    depends_on:
      - postgres
    environment:
      XDEBUG_MODE: off
      XDEBUG_CONFIG:
          client_host=172.17.0.1
          client_port=9003
          start_with_request=yes
    volumes:
      - ./:/var/www/html
      - ../../logs/${APP_NAME}/php/:/var/log/php
      - ../../docker/${APP_NAME}/php-fpm/php/custom.ini:/usr/local/etc/php/php.ini
      - ../../docker/${APP_NAME}/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ../../docker/${APP_NAME}/php-fpm/php-fpm.d/:/usr/local/etc/php-fpm.d
      - ../../docker/${APP_NAME}/php-fpm/socket/:/var/run/php
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9003:9003"
  apache:
    container_name: ${APP_NAME}-apache
    build:
      context: .
      dockerfile: ../../docker/${APP_NAME}/apache/Dockerfile
    volumes:
      - ./:/var/www/html
      - ../../docker/${APP_NAME}/apache/conf:/usr/local/apache2/conf
      - ../../logs/${APP_NAME}/apache:/usr/local/apache2/logs:rw
      - ../../docker/${APP_NAME}/apache/uploads:/usr/local/apache2/uploads
      - ../../docker/${APP_NAME}/php-fpm/socket/:/var/run/php
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    extra_hosts:
      - host.docker.internal:${HOST_IP:-172.20.0.1}
